{
  "$schema": "https://opencode.ai/theme.json",
  "defs": {
    "background": "{{ background }}",
    "foreground": "{{ foreground }}",
    "accent": "{{ accent }}",
    "panel": "{{ mix background foreground 6% }}",
    "element": "{{ mix background foreground 10% }}",
    "border": "{{ mix background foreground 30% }}",
    "borderSubtle": "{{ mix background foreground 18% }}",
    "muted": "{{ mix foreground background 34% }}",
    "diffAddedBg": "{{ mix background green 15% }}",
    "diffRemovedBg": "{{ mix background red 15% }}",
    "diffContextBg": "{{ mix background foreground 6% }}"
  },
  "theme": {
    "primary": "accent",
    "secondary": "{{ magenta }}",
    "accent": "accent",
    "error": "{{ red }}",
    "warning": "{{ yellow }}",
    "success": "{{ green }}",
    "info": "{{ blue }}",
    "text": "foreground",
    "textMuted": "muted",
    "background": "background",
    "backgroundPanel": "panel",
    "backgroundElement": "element",
    "border": "border",
    "borderActive": "accent",
    "borderSubtle": "borderSubtle",
    "diffAdded": "{{ green }}",
    "diffRemoved": "{{ red }}",
    "diffContext": "muted",
    "diffHunkHeader": "{{ cyan }}",
    "diffHighlightAdded": "{{ bright_green }}",
    "diffHighlightRemoved": "{{ bright_red }}",
    "diffAddedBg": "diffAddedBg",
    "diffRemovedBg": "diffRemovedBg",
    "diffContextBg": "diffContextBg",
    "diffLineNumber": "muted",
    "diffAddedLineNumberBg": "{{ mix background green 8% }}",
    "diffRemovedLineNumberBg": "{{ mix background red 8% }}",
    "markdownText": "foreground",
    "markdownHeading": "{{ magenta }}",
    "markdownLink": "accent",
    "markdownLinkText": "{{ cyan }}",
    "markdownCode": "{{ cyan }}",
    "markdownBlockQuote": "muted",
    "markdownEmph": "{{ yellow }}",
    "markdownStrong": "accent",
    "markdownHorizontalRule": "borderSubtle",
    "markdownListItem": "{{ magenta }}",
    "markdownListEnumeration": "{{ magenta }}",
    "markdownImage": "accent",
    "markdownImageText": "{{ cyan }}",
    "markdownCodeBlock": "foreground",
    "syntaxComment": "{{ mix foreground background 52% }}",
    "syntaxKeyword": "{{ magenta }}",
    "syntaxFunction": "{{ blue }}",
    "syntaxVariable": "accent",
    "syntaxString": "{{ green }}",
    "syntaxNumber": "{{ yellow }}",
    "syntaxType": "{{ blue }}",
    "syntaxOperator": "{{ magenta }}",
    "syntaxPunctuation": "muted"
  }
}
